version: "3.91"
services:
  flaskApp:
    build:
      context: .
      dockerfile: Dockerfile-flask
    image: local_image/flask_rq
    stop_signal: SIGINT
    ports:
      - ${flask_app_ports}

  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    image: local_image/ml_worker
