version: "3.91"
services:
  flaskApp:
    build:
      context: .
      dockerfile: Dockerfile
    image: local_image/flask_rq
    stop_signal: SIGINT
    volumes:
      - type: bind
        source: ${flask_source_dir}
        target: /app
      - type: bind
        source: ${model_lib_source_dir}
        target: /app/model
      - type: bind
        source: ${dal_lib_source_dir}
        target: /app/DAL
    ports:
      - ${flask_app_ports}
    command: python app_factory.py

    depends_on:
      - minio

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: local_image/ml_worker
    volumes:
      - type: bind
        source: ${worker_source_dir}
        target: /app
      - type: bind
        source: ${model_lib_source_dir}
        target: /app/model
      - type: bind
        source: ${dal_lib_source_dir}
        target: /app/DAL
    command: python worker.py

    depends_on:
      - redis
      - minio

  redis:
    hostname: redis
    image: redis:latest
    ports:
      - ${redis_port}

  minio:
    image: docker.io/bitnami/minio
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    ports:
      - ${minio_port_1}
      - ${minio_port_2}